### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by loisra01** [LexisNexis-GHA-Public/action-github-app-auth#16]
Please update LexisNexis-GHA-Public/action-github-app-auth@v1 to use Node.js 20

**Comment by loisra01** [comment]
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by felipebaisi** [comment]
https://github.com/LexisNexis-GHA-Public/action-github-app-auth/pull/17

**Comment by felipebaisi** [comment]
Fixed on https://github.com/LexisNexis-GHA-Public/action-github-app-auth/releases/tag/v1.4.0 
V1 Updated too: https://github.com/LexisNexis-GHA-Public/action-github-app-auth/releases/tag/v1
