### ISSUE TITLE
Error when running action: started on 10/12/2022

### ISSUE THREAD

**Issue by grioda01** [LexisNexis-GHA-Public/action-github-app-auth#6]
Hello, 
I have been using for almost a year now the action LexisNexis-GHA-Public/action-github-app-auth@v1 in my action to build the JWT token out of a github app. Today, suddenly, I am getting the following error when running the action-github-app-auth. Please help.

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: Not able to retrieve the installation access token: HttpError: 'Expiration time' claim ('exp') is too far in the future
(node:15) UnhandledPromiseRejectionWarning: Error: Not able to retrieve the installation access token: HttpError: 'Expiration time' claim ('exp') is too far in the future
    at /__w/_actions/LexisNexis-GHA-Public/action-github-app-auth/v1/dist/index.js:156:19
    at Generator.throw (<anonymous>)
    at rejected (/__w/_actions/LexisNexis-GHA-Public/action-github-app-auth/v1/dist/index.js:71:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15) [DEP001[8](https://github.com/LexisNexis-RBA/bsvelk-project-hermes/actions/runs/3239681736/jobs/5309352531#step:3:9)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by felipebaisi** [comment]
Yep - this is not just for us. GH deprecated set set-output command. <br>https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ <br>
I will fix that.

**Comment by felipebaisi** [comment]
[Fhttps://github.com/LexisNexis-GHA-Public/action-github-app-auth/pull/7](https://github.com/LexisNexis-GHA-Public/action-github-app-auth/pull/7)

**Comment by grioda01** [comment]
@felipebaisi 
After switching to your newest version I am getting now another error
```
Run LexisNexis-GHA-Public/action-github-app-auth@v1 
5/usr/bin/docker exec f6fc48ffe1bdf5eeab033600a9cb435ce68de4fbb5180f4decc59ed3057c748f sh -c "cat /etc/*release | grep ^ID" 
6/__w/_actions/LexisNexis-GHA-Public/action-github-app-auth/v1/dist/index.js:5385 
7 const error = new requestError.RequestError(toErrorMessage(data), status, { 
8 ^ 
9 
10RequestError [HttpError]: 'Expiration time' claim ('exp') is too far in the future 
11 at /__w/_actions/LexisNexis-GHA-Public/action-github-app-auth/v1/dist/index.js:5385:21 
12 at processTicksAndRejections (node:internal/process/task_queues:96:5) 
13 at async hook (/__w/_actions/LexisNexis-GHA-Public/action-github-app-auth/v1/dist/index.js:2210:18) { 
14 status: 401, 
15 response: { 
16 url: 'https://api.github.com/app/installations', 
17 status: 401, 
18 headers: { 
19 'access-control-allow-origin': '*', 
20 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 
21 connection: 'close', 
22 'content-length': '121', 
23 'content-security-policy': "default-src 'none'", 
24 'content-type': 'application/json; charset=utf-8', 
25 date: 'Fri, 11 Nov 2022 17:03:25 GMT', 
26 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 
27 server: 'GitHub.com', 
28 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 
29 vary: 'Accept-Encoding, Accept, X-Requested-With', 
30 'x-content-type-options': 'nosniff', 
31 'x-frame-options': 'deny', 
32 'x-github-media-type': 'github.v3; format=json', 
33 'x-github-request-id': '28A2:7359:FE999D:2082E5A:636E805D', 
34 'x-xss-protection': '0' 
35 }, 
36 data: { 
37 message: "'Expiration time' claim ('exp') is too far in the future", 
38 documentation_url: 'https://docs.github.com/rest' 
39 } 
40 }, 
41 request: { 
42 method: 'GET', 
43 url: 'https://api.github.com/app/installations', 
44 headers: { 
45 accept: 'application/vnd.github.v3+json', 
46 'user-agent': 'octokit-rest.js/19.0.5 octokit-core.js/4.1.0 Node.js/16.13.0 (linux; x64)', 
47 authorization: 'bearer [REDACTED]' 
48 }, 
49 request: { hook: [Function: bound bound register] } 
50 } 
51}
```
